document.addEventListener('DOMContentLoaded', () => {
    const phrases = [
        // Did you think I was an AI? No, my creator does not have the funds to have an API key
        "The Lord is my shepherd; I shall not want. - Psalm 23:1",
    "For God so loved the world, that he gave his only Son, that whoever believes in him should not perish but have eternal life. - John 3:16",
    "I can do all things through Christ who strengthens me. - Philippians 4:13",
    "For I know the plans I have for you, declares the Lord, plans for welfare and not for evil, to give you a future and a hope. - Jeremiah 29:11",
    "But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness. - Galatians 5:22",
    "The Lord is my light and my salvation—whom shall I fear? The Lord is the stronghold of my life—of whom shall I be afraid? - Psalm 27:1",
    "For we walk by faith, not by sight. - 2 Corinthians 5:7",
    "The name of the Lord is a strong tower; the righteous run to it and are safe. - Proverbs 18:10",
    "Trust in the Lord with all your heart and lean not on your own understanding. - Proverbs 3:5",
    "Be still, and know that I am God. - Psalm 46:10",
    "The Lord will fight for you; you need only to be still. - Exodus 14:14",
    "The Lord is near to all who call on him, to all who call on him in truth. - Psalm 145:18",
    "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. - Philippians 4:6",
    "Cast all your anxiety on him because he cares for you. - 1 Peter 5:7",
    "For it is by grace you have been saved, through faith—and this is not from yourselves, it is the gift of God. - Ephesians 2:8",
    "The Lord is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge. - Psalm 18:2",
    "But those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint. - Isaiah 40:31",
    "Blessed are the pure in heart, for they shall see God. - Matthew 5:8",
    "The Lord bless you and keep you; the Lord make his face shine on you and be gracious to you. - Numbers 6:24-25",
    "Rejoice in the Lord always. I will say it again: Rejoice! - Philippians 4:4",
    "The righteous cry out, and the Lord hears them; he delivers them from all their troubles. - Psalm 34:17",
    "And we know that in all things God works for the good of those who love him, who have been called according to his purpose. - Romans 8:28",
    "The Lord is good, a refuge in times of trouble. He cares for those who trust in him. - Nahum 1:7",
    "I sought the Lord, and he answered me; he delivered me from all my fears. - Psalm 34:4",
    "The Lord is compassionate and gracious, slow to anger, abounding in love. - Psalm 103:8",
    "For the word of God is alive and active. Sharper than any double-edged sword. - Hebrews 4:12",
    "The Lord is close to the brokenhearted and saves those who are crushed in spirit. - Psalm 34:18",
    "For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord. - Romans 6:23",
    "Taste and see that the Lord is good; blessed is the one who takes refuge in him. - Psalm 34:8",
    "The Lord is my strength and my song; he has given me victory. - Exodus 15:2",
    "The grass withers and the flowers fall, but the word of our God endures forever. - Isaiah 40:8",
    "The Lord is righteous in all his ways and faithful in all he does. - Psalm 145:17",
    "Come to me, all you who are weary and burdened, and I will give you rest. - Matthew 11:28",
    "The Lord is gracious and full of compassion, slow to anger and great in mercy. - Psalm 145:8",
    "He gives strength to the weary and increases the power of the weak. - Isaiah 40:29",
    "For I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers, neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God that is in Christ Jesus our Lord. - Romans 8:38-39",
    "The Lord will guide you always; he will satisfy your needs in a sun-scorched land and will strengthen your frame. - Isaiah 58:11",
    "For the Lord is good and his love endures forever; his faithfulness continues through all generations. - Psalm 100:5",
    "Even though I walk through the darkest valley, I will fear no evil, for you are with me; your rod and your staff, they comfort me. - Psalm 23:4",
    "The Lord is my strength and my defense; he has become my salvation. - Psalm 118:14",
    "Do not let your hearts be troubled. You believe in God; believe also in me. - John 14:1",
    "The Lord is a refuge for the oppressed, a stronghold in times of trouble. - Psalm 9:9",
    "For he will command his angels concerning you to guard you in all your ways. - Psalm 91:11",
    "The Lord is righteous; he loves righteousness; the upright shall behold his face. - Psalm 11:7",
    "But he was pierced for our transgressions, he was crushed for our iniquities; the punishment that brought us peace was on him, and by his wounds, we are healed. - Isaiah 53:5",
    "The Lord is my helper; I will not be afraid. What can mere mortals do to me? - Hebrews 13:6",
    "He will wipe every tear from their eyes. There will be no more death or mourning or crying or pain, for the old order of things has passed away. - Revelation 21:4",
    "The Lord is my strength and my song; he has become my salvation. - Psalm 118:14",
    "For where two or three gather in my name, there am I with them. - Matthew 18:20",
    "The Lord is my portion, says my soul, therefore I will hope in him. - Lamentations 3:24",
    "For we live by faith, not by sight. - 2 Corinthians 5:7",
    "The Lord is good, a stronghold in the day of trouble; he knows those who take refuge in him. - Nahum 1:7",
    "Give thanks to the Lord, for he is good; his love endures forever. - 1 Chronicles 16:34",
    "The Lord is near to the brokenhearted and saves the crushed in spirit. - Psalm 34:18",
    "But those who wait for the Lord shall renew their strength; they shall mount up with wings like eagles; they shall run and not be weary; they shall walk and not faint. - Isaiah 40:31",
    "The Lord is a God of justice; blessed are all who wait for him. - Isaiah 30:18",
    "For the Lord your God is with you wherever you go. - Joshua 1:9",
    "The Lord is my strength and my shield; my heart trusts in him, and he helps me. - Psalm 28:7",
    "Let everything that has breath praise the Lord. - Psalm 150:6",
    "The Lord is my rock and my fortress and my deliverer, my God, my rock, in whom I take refuge. - Psalm 18:2",
    "The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid? - Psalm 27:1",
    "The Lord is gracious and righteous; our God is full of compassion. - Psalm 116:5",
    "For the Lord your God is the one who goes with you to fight for you against your enemies to give you victory. - Deuteronomy 20:4",
    "The Lord is good to all; he has compassion on all he has made. - Psalm 145:9",
    "The Lord is my portion; therefore I will wait for him. - Lamentations 3:24",
    "The Lord is my shepherd; I lack nothing. - Psalm 23:1",
    "The Lord is my strength and my shield; my heart trusts in him, and he helps me. - Psalm 28:7",
    "The Lord is with me; I will not be afraid. What can mere mortals do to me? - Psalm 118:6",
    "The Lord is righteous in all his ways and faithful in all he does. - Psalm 145:17",
    "The Lord is good to those whose hope is in him, to the one who seeks him. - Lamentations 3:25",
    "The Lord is my strength and my defense; he has become my salvation. - Exodus 15:2",
    "The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid? - Psalm 27:1",
    "The Lord is compassionate and gracious, slow to anger, abounding in love. - Psalm 103:8",
    "The Lord is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge. - Psalm 18:2",
    "The Lord is near to all who call on him, to all who call on him in truth. - Psalm 145:18",
    "The Lord is good to all; he has compassion on all he has made. - Psalm 145:9",
    "The Lord is a refuge for the oppressed, a stronghold in times of trouble. - Psalm 9:9",
    "The Lord is faithful to all his promises and loving toward all he has made. - Psalm 145:13",
    "The Lord is my portion, says my soul, therefore I will hope in him. - Lamentations 3:24",
    "The Lord is with me; I will not be afraid. What can man do to me? - Psalm 118:6",
    "The Lord is near to the brokenhearted and saves the crushed in spirit. - Psalm 34:18",
    "The Lord is a warrior; the Lord is his name. - Exodus 15:3",
    "The Lord is righteous in all his ways and faithful in all he does. - Psalm 145:17",
    "The Lord is my light and my salvation—whom shall I fear? The Lord is the stronghold of my life—of whom shall I be afraid? - Psalm 27:1",
    "The Lord is good, a refuge in times of trouble. He cares for those who trust in him. - Nahum 1:7",
    "The Lord is gracious and righteous; our God is full of compassion. - Psalm 116:5",
    "The Lord is my portion; I promise to keep your words. - Psalm 119:57",
    "The Lord is good to all; he has compassion on all he has made. - Psalm 145:9",
    "The Lord is righteous in all his ways and faithful in all he does. - Psalm 145:17",
    "The Lord is good to those whose hope is in him, to the one who seeks him. - Lamentations 3:25",
    "The Lord is my strength and my defense; he has become my salvation. - Psalm 118:14",
    "The Lord is near to all who call on him, to all who call on him in truth. - Psalm 145:18",
    "The Lord is faithful to all his promises and loving toward all he has made. - Psalm 145:13",
    "The Lord is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge. - Psalm 18:2",
    "The Lord is near to the brokenhearted and saves the crushed in spirit. - Psalm 34:18",
    "The Lord is my shepherd; I lack nothing. - Psalm 23:1",
    "The Lord is a refuge for the oppressed, a stronghold in times of trouble. - Psalm 9:9",
    "The Lord is righteous in all his ways and faithful in all he does. - Psalm 145:17",
    "The Lord is with me; I will not be afraid. What can man do to me? - Psalm 118:6",
    "The Lord is my portion; therefore I will wait for him. - Lamentations 3:24",
    "The Lord is compassionate and gracious, slow to anger, abounding in love. - Psalm 103:8",
    "The Lord is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge. - Psalm 18:2",
    "The Lord is my light and my salvation—whom shall I fear? The Lord is the stronghold of my life—of whom shall I be afraid? - Psalm 27:1",
    "The Lord is good, a refuge in times of trouble. He cares for those who trust in him. - Nahum 1:7",
    "The Lord is near to all who call on him, to all who call on him in truth. - Psalm 145:18",
    "The Lord is gracious and righteous; our God is full of compassion. - Psalm 116:5",
    "The Lord is my portion; I promise to keep your words. - Psalm 119:57",
    "The Lord is good to all; he has compassion on all he has made. - Psalm 145:9",
    "The Lord is righteous in all his ways and faithful in all he does. - Psalm 145:17",
    "The Lord is good to those whose hope is in him, to the one who seeks him. - Lamentations 3:25",
    "The Lord is my strength and my defense; he has become my salvation. - Psalm 118:14",
    "The Lord is near to all who call on him, to all who call on him in truth. - Psalm 145:18",
    "The Lord is faithful to all his promises and loving toward all he has made. - Psalm 145:13",
    "The Lord is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge. - Psalm 18:2",
    "The Lord is near to the brokenhearted and saves the crushed in spirit. - Psalm 34:18",
    "The Lord is my shepherd; I lack nothing. - Psalm 23:1",
    "The Lord is a refuge for the oppressed, a stronghold in times of trouble. - Psalm 9:9",
    "The Lord is righteous in all his ways and faithful in all he does. - Psalm 145:17",
    "The Lord is with me; I will not be afraid. What can man do to me? - Psalm 118:6",
    "The Lord is my portion; therefore I will wait for him. - Lamentations 3:24",
    "The Lord is compassionate and gracious, slow to anger, abounding in love. - Psalm 103:8",
    "The Lord is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge. - Psalm 18:2",
    "The Lord is my light and my salvation—whom shall I fear? The Lord is the stronghold of my life—of whom shall I be afraid? - Psalm 27:1",
    "The Lord is good, a refuge in times of trouble. He cares for those who trust in him. - Nahum 1:7",
    "The Lord is near to all who call on him, to all who call on him in truth. - Psalm 145:18",
    "The Lord is gracious and righteous; our God is full of compassion. - Psalm 116:5",
    "The Lord is my portion; I promise to keep your words. - Psalm 119:57",
    "The Lord is good to all; he has compassion on all he has made. - Psalm 145:9",
    "The Lord is righteous in all his ways and faithful in all he does. - Psalm 145:17",
    "The Lord is good to those whose hope is in him, to the one who seeks him. - Lamentations 3:25",
    "The Lord is my strength and my defense; he has become my salvation. - Psalm 118:14",
    "The Lord is near to all who call on him, to all who call on him in truth. - Psalm 145:18",
    "The Lord is faithful to all his promises and loving toward all he has made. - Psalm 145:13",
    "The Lord is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge. - Psalm 18:2",
    "The Lord is near to the brokenhearted and saves the crushed in spirit. - Psalm 34:18",
    "The Lord is my shepherd; I lack nothing. - Psalm 23:1",
    "The Lord is a refuge for the oppressed, a stronghold in times of trouble. - Psalm 9:9",
    "The Lord is righteous in all his ways and faithful in all he does. - Psalm 145:17",
    "The Lord is with me; I will not be afraid. What can man do to me? - Psalm 118:6",
    "The Lord is my portion; therefore I will wait for him. - Lamentations 3:24",
    "The Lord is compassionate and gracious, slow to anger, abounding in love. - Psalm 103:8",
    "The Lord is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge. - Psalm 18:2",
    "The Lord is my light and my salvation—whom shall I fear? The Lord is the stronghold of my life—of whom shall I be afraid? - Psalm 27:1",
    "The Lord is good, a refuge in times of trouble. He cares for those who trust in him. - Nahum 1:7",
    "The Lord is near to all who call on him, to all who call on him in truth. - Psalm 145:18",
    "The Lord is gracious and righteous; our God is full of compassion. - Psalm 116:5",
    "The Lord is my portion; I promise to keep your words. - Psalm 119:57",
    "The Lord is good to all; he has compassion on all he has made. - Psalm 145:9",
    "The Lord is righteous in all his ways and faithful in all he does. - Psalm 145:17",
    "The Lord is good to those whose hope is in him, to the one who seeks him. - Lamentations 3:25",
    "The Lord is my strength and my defense; he has become my salvation. - Psalm 118:14",
    "The Lord is near to all who call on him, to all who call on him in truth. - Psalm 145:18",
    "The Lord is faithful to all his promises and loving toward all he has made. - Psalm 145:13",
    "The Lord is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge. - Psalm 18:2",
    "The Lord is near to the brokenhearted and saves the crushed in spirit. - Psalm 34:18",
    "The Lord is my shepherd; I lack nothing. - Psalm 23:1",
    "The Lord is a refuge for the oppressed, a stronghold in times of trouble. - Psalm 9:9",
    "The Lord is righteous in all his ways and faithful in all he does. - Psalm 145:17",
    "The Lord is with me; I will not be afraid. What can man do to me? - Psalm 118:6",
    "The Lord is my portion; therefore I will wait for him. - Lamentations 3:24",
    "The Lord is compassionate and gracious, slow to anger, abounding in love. - Psalm 103:8",
    "The Lord is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge. - Psalm 18:2",
    "The Lord is my light and my salvation—whom shall I fear? The Lord is the stronghold of my life—of whom shall I be afraid? - Psalm 27:1",
    "The Lord is good, a refuge in times of trouble. He cares for those who trust in him. - Nahum 1:7",
    "The Lord is near to all who call on him, to all who call on him in truth. - Psalm 145:18",
    "The Lord is gracious and righteous; our God is full of compassion. - Psalm 116:5",
    "The Lord is my portion; I promise to keep your words. - Psalm 119:57",
    "The Lord is good to all; he has compassion on all he has made. - Psalm 145:9",
    "The Lord is righteous in all his ways and faithful in all he does. - Psalm 145:17",
    "The Lord is good to those whose hope is in him, to the one who seeks him. - Lamentations 3:25",
    "The Lord is my strength and my defense; he has become my salvation. - Psalm 118:14",
    "The Lord is near to all who call on him, to all who call on him in truth. - Psalm 145:18",
    "The Lord is faithful to all his promises and loving toward all he has made. - Psalm 145:13",
    "The Lord is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge. - Psalm 18:2",
    "The Lord is near to the brokenhearted and saves the crushed in spirit. - Psalm 34:18",
    "The Lord is my shepherd; I lack nothing. - Psalm 23:1",
    "The Lord is a refuge for the oppressed, a stronghold in times of trouble. - Psalm 9:9",
    "The Lord is righteous in all his ways and faithful in all he does. - Psalm 145:17",
    "The Lord is with me; I will not be afraid. What can man do to me? - Psalm 118:6",
    "The Lord is my portion; therefore I will wait for him. - Lamentations 3:24",
    "The Lord is compassionate and gracious, slow to anger, abounding in love. - Psalm 103:8",
    "The Lord is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge. - Psalm 18:2",
    "The Lord is my light and my salvation—whom shall I fear? The Lord is the stronghold of my life—of whom shall I be afraid? - Psalm 27:1",
    "The Lord is good, a refuge in times of trouble. He cares for those who trust in him. - Nahum 1:7",
    "The Lord is near to all who call on him, to all who call on him in truth. - Psalm 145:18",
    "The Lord is gracious and righteous; our God is full of compassion. - Psalm 116:5",
    "The Lord is my portion; I promise to keep your words. - Psalm 119:57",
    "The Lord is good to all; he has compassion on all he has made. - Psalm 145:9",
    "The Lord is righteous in all his ways and faithful in all he does. - Psalm 145:17",
    "The Lord is good to those whose hope is in him, to the one who seeks him. - Lamentations 3:25",
    "The Lord is my strength and my defense; he has become my salvation. - Psalm 118:14",
    "The Lord is near to all who call on him, to all who call on him in truth. - Psalm 145:18",
    "The Lord is faithful to all his promises and loving toward all he has made. - Psalm 145:13",
    "The Lord is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge. - Psalm 18:2",
    "The Lord is near to the brokenhearted and saves the crushed in spirit. - Psalm 34:18",
    "The Lord is my shepherd; I lack nothing. - Psalm 23:1",
    "The Lord is a refuge for the oppressed, a stronghold in times of trouble. - Psalm 9:9",
    "The Lord is righteous in all his ways and faithful in all he does. - Psalm 145:17",
    "The Lord is with me; I will not be afraid. What can man do to me? - Psalm 118:6",
    "The Lord is my portion; therefore I will wait for him. - Lamentations 3:24",
    "The Lord is compassionate and gracious, slow to anger, abounding in love. - Psalm 103:8",
    "The Lord is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge. - Psalm 18:2",
    "The Lord is my light and my salvation—whom shall I fear? The Lord is the stronghold of my life—of whom shall I be afraid? - Psalm 27:1",
    "The Lord is good, a refuge in times of trouble. He cares for those who trust in him. - Nahum 1:7",
    "The Lord is near to all who call on him, to all who call on him in truth. - Psalm 145:18",
    "The Lord is gracious and righteous; our God is full of compassion. - Psalm 116:5",
    "The Lord is my portion; I promise to keep your words. - Psalm 119:57",
    "The Lord is good to all; he has compassion on all he has made. - Psalm 145:9",
    "The Lord is righteous in all his ways and faithful in all he does. - Psalm 145:17",
    "The Lord is good to those whose hope is in him, to the one who seeks him. - Lamentations 3:25",
    "The Lord is my strength and my defense; he has become my salvation. - Psalm 118:14",
    "The Lord is near to all who call on him, to all who call on him in truth. - Psalm 145:18",
    "The Lord is faithful to all his promises and loving toward all he has made. - Psalm 145:13",
    "The Lord is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge. - Psalm 18:2",
    "The Lord is near to the brokenhearted and saves the crushed in spirit. - Psalm 34:18",
    "The Lord is my shepherd; I lack nothing. - Psalm 23:1",
    "The Lord is a refuge for the oppressed, a stronghold in times of trouble. - Psalm 9:9",
    "The Lord is righteous in all his ways and faithful in all he does. - Psalm 145:17",
    "The Lord is with me; I will not be afraid. What can man do to me? - Psalm 118:6",
    "The Lord is my portion; therefore I will wait for him. - Lamentations 3:24",
    "The Lord is compassionate and gracious, slow to anger, abounding in love. - Psalm 103:8",
    "The Lord is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge. - Psalm 18:2",
    "The Lord is my light and my salvation—whom shall I fear? The Lord is the stronghold of my life—of whom shall I be afraid? - Psalm 27:1",
    "The Lord is good, a refuge in times of trouble. He cares for those who trust in him. - Nahum 1:7",
    "The Lord is near to all who call on him, to all who call on him in truth. - Psalm 145:18",
    "The Lord is gracious and righteous; our God is full of compassion. - Psalm 116:5",
    "The Lord is my portion; I promise to keep your words. - Psalm 119:57",
    "The Lord is good to all; he has compassion on all he has made. - Psalm 145:9",
    "The Lord is righteous in all his ways and faithful in all he does. - Psalm 145:17",
    "The Lord is good to those whose hope is in him, to the one who seeks him. - Lamentations 3:25",
    "The Lord is my strength and my defense; he has become my salvation. - Psalm 118:14",
    "The Lord is near to all who call on him, to all who call on him in truth. - Psalm 145:18",
    "The Lord is faithful to all his promises and loving toward all he has made. - Psalm 145:13",
    "The Lord is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge. - Psalm 18:2",
    "The Lord is near to the brokenhearted and saves the crushed in spirit. - Psalm 34:18",
    "The Lord is my shepherd; I lack nothing. - Psalm 23:1",
    "The Lord is a refuge for the oppressed, a stronghold in times of trouble. - Psalm 9:9",
    "The Lord is righteous in all his ways and faithful in all he does. - Psalm 145:17",
    "The Lord is with me; I will not be afraid. What can man do to me? - Psalm 118:6",
    "The Lord is my portion; therefore I will wait for him. - Lamentations 3:24",
    "The Lord is compassionate and gracious, slow to anger, abounding in love. - Psalm 103:8",
    "The Lord is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge. - Psalm 18:2",
    "The Lord is my light and my salvation—whom shall I fear? The Lord is the stronghold of my life—of whom shall I be afraid? - Psalm 27:1",
    "The Lord is good, a refuge in times of trouble. He cares for those who trust in him. - Nahum 1:7",
    "The Lord is near to all who call on him, to all who call on him in truth. - Psalm 145:18",
    "The Lord is gracious and righteous; our God is full of compassion. - Psalm 116:5",
    "The Lord is my portion; I promise to keep your words. - Psalm 119:57",
    "The Lord is good to all; he has compassion on all he has made. - Psalm 145:9",
    "The Lord is righteous in all his ways and faithful in all he does. - Psalm 145:17",
    "The Lord is good to those whose hope is in him, to the one who seeks him. - Lamentations 3:25",
    "The Lord is my strength and my defense; he has become my salvation. - Psalm 118:14",
    "The Lord is near to all who call on him, to all who call on him in truth. - Psalm 145:18",
    "The Lord is faithful to all his promises and loving toward all he has made. - Psalm 145:13",
    "The Lord is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge. - Psalm 18:2",
    "The Lord is near to the brokenhearted and saves the crushed in spirit. - Psalm 34:18",
    "The Lord is my shepherd; I lack nothing. - Psalm 23:1",
    "The Lord is a refuge for the oppressed, a stronghold in times of trouble. - Psalm 9:9",
    "The Lord is righteous in all his ways and faithful in all he does. - Psalm 145:17",
    "The Lord is with me; I will not be afraid. What can man do to me? - Psalm 118:6",
    "The Lord is my portion; therefore I will wait for him. - Lamentations 3:24",
    "The Lord is compassionate and gracious, slow to anger, abounding in love. - Psalm 103:8",
    "The Lord is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge. - Psalm 18:2",
    "The Lord is my light and my salvation—whom shall I fear? The Lord is the stronghold of my life—of whom shall I be afraid? - Psalm 27:1",
    "The Lord is good, a refuge in times of trouble. He cares for those who trust in him. - Nahum 1:7",
    "The Lord is near to all who call on him, to all who call on him in truth. - Psalm 145:18",
    "The Lord is gracious and righteous; our God is full of compassion. - Psalm 116:5",
    "The Lord is my portion; I promise to keep your words. - Psalm 119:57",
    "The Lord is good to all; he has compassion on all he has made. - Psalm 145:9",
    "The Lord is righteous in all his ways and faithful in all he does. - Psalm 145:17",
    "The Lord is good to those whose hope is in him, to the one who seeks him. - Lamentations 3:25",
    "The Lord is my strength and my defense; he has become my salvation. - Psalm 118:14",
    "The Lord is near to all who call on him, to all who call on him in truth. - Psalm 145:18",
    "The Lord is faithful to all his promises and loving toward all he has made. - Psalm 145:13",
    "The Lord is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge. - Psalm 18:2",
    "The Lord is near to the brokenhearted and saves the crushed in spirit. - Psalm 34:18",
    "The Lord is my shepherd; I lack nothing. - Psalm 23:1",
    "The Lord is a refuge for the oppressed, a stronghold in times of trouble. - Psalm 9:9",
    "The Lord is righteous in all his ways and faithful in all he does. - Psalm 145:17",
    "The Lord is with me; I will not be afraid. What can man do to me? - Psalm 118:6",
    "The Lord is my portion; therefore I will wait for him. - Lamentations 3:24",
    "The Lord is compassionate and gracious, slow to anger, abounding in love. - Psalm 103:8",
    "The Lord is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge. - Psalm 18:2",
    "The Lord is my light and my salvation—whom shall I fear? The Lord is the stronghold of my life—of whom shall I be afraid? - Psalm 27:1",
    "The Lord is good, a refuge in times of trouble. He cares for those who trust in him. - Nahum 1:7",
    "The Lord is near to all who call on him, to all who call on him in truth. - Psalm 145:18",
    "The Lord is gracious and righteous; our God is full of compassion. - Psalm 116:5",
    "The Lord is my portion; I promise to keep your words. - Psalm 119:57",
    "The Lord is good to all; he has compassion on all he has made. - Psalm 145:9",
    "The Lord is righteous in all his ways and faithful in all he does. - Psalm 145:17",
    "The Lord is good to those whose hope is in him, to the one who seeks him. - Lamentations 3:25",
    "The Lord is my strength and my defense; he has become my salvation. - Psalm 118:14",
    "The Lord is near to all who call on him, to all who call on him in truth. - Psalm 145:18",
    "The Lord is faithful to all his promises and loving toward all he has made. - Psalm 145:13",
    "The Lord is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge. - Psalm 18:2",
    "The Lord is near to the brokenhearted and saves the crushed in spirit. - Psalm 34:18"
    ];
    
    const imageContainer = document.getElementById('imageContainer');
    const speechBubble = document.getElementById('speechBubble');
    let timeout;
  
    imageContainer.addEventListener('click', () => {
      clearTimeout(timeout); 
      const randomPhrase = phrases[Math.floor(Math.random() * phrases.length)];
      speechBubble.textContent = randomPhrase;
      speechBubble.style.display = 'block';
  
      timeout = setTimeout(() => {
        speechBubble.style.display = 'none';
      }, 10000); 
    });

    function showRandomPhrase() {
      clearTimeout(timeout); 
      const randomPhrase = phrases[Math.floor(Math.random() * phrases.length)];
      speechBubble.textContent = randomPhrase;
      speechBubble.style.display = 'block';
    
      timeout = setTimeout(() => {
        speechBubble.style.display = 'none';
      }, 10000); 
    }
    
 
    showRandomPhrase();
    
    setInterval(showRandomPhrase, 300000);
    
  });

